apiVersion: apps/v1
kind: Deployment
metadata:
  name: imageproc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: imageproc
  template:
    metadata:
      labels:
        app: imageproc
    spec:
      containers:
        - name: imageproc
          image: synthao/imgproc:v1.0.0
          ports:
            - containerPort: 50051
            - containerPort: 7070 # Добавьте этот порт для HTTP
          readinessProbe:
            httpGet:
              path: /ping
              port: 7070
            initialDelaySeconds: 5
            periodSeconds: 10
          env:
            - name: GRPC_SERVER_ADDRESS
              value: "0.0.0.0:50051"
            - name: LOG_LEVEL
              value: "DEBUG"
            - name: HTTP_SERVER_HOST
              value: "0.0.0.0"
            - name: HTTP_SERVER_PORT
              value: "7070"