apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "123456" # $(echo -n "POSTGRES_PASSWORD" | base64)
  POSTGRES_DB: "meetme" # DB name