apiVersion: v1
kind: Service
metadata:
  name: meetme
spec:
  type: NodePort
  selector:
    app: meetme
  ports:
    - protocol: TCP
      # Порт, на котором сервис будет доступен внутри кластера. Другие поды могут обращаться к этому сервису по этому порту
      port: 8080
      # Порт в поде, на который будет перенаправлен трафик.
      # В данном случае, он совпадает с port, но может быть другим, если приложение в поде слушает на другом порту
      targetPort: 8080
      # Порт, который будет открыт на каждом узле кластера для доступа к сервису извне.
      # Этот порт должен быть в диапазоне 30000-32767
      nodePort: 30001
